# Generated by Django 5.0.1 on 2025-11-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpfCnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('mobilePhone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('addressNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('postalCode', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('asaas_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Asaas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('synced_with_asaas', models.BooleanField(default=False, verbose_name='Sincronizado com Asaas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cycle', models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUALLY', 'Semestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Ciclo')),
                ('billing_type', models.CharField(choices=[('BOLETO', 'Boleto Bancário'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'PIX'), ('UNDEFINED', 'Indefinido')], default='BOLETO', max_length=20, verbose_name='Forma de Pagamento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('next_due_date', models.DateField(verbose_name='Próximo Vencimento')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('max_payments', models.IntegerField(blank=True, help_text='Deixe em branco para cobranças ilimitadas', null=True, verbose_name='Número Máximo de Cobranças')),
                ('asaas_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Asaas')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('EXPIRED', 'Expirada')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('synced_with_asaas', models.BooleanField(default=False, verbose_name='Sincronizado com Asaas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to='asaas_app.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Recorrência',
                'verbose_name_plural': 'Recorrências',
                'ordering': ['-created_at'],
            },
        ),
    ]
