# Generated by Django 4.2.7 on 2025-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observations',
            field=models.TextField(blank=True, help_text='Id do cliente no TalkIAChat', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='recorrencia',
            name='billing_type',
            field=models.CharField(choices=[('BOLETO', 'Boleto Bancário'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'Pix'), ('UNDEFINED', 'Perguntar ao Cliente')], default='BOLETO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
