# Generated by Django 5.0.1 on 2025-11-04 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_app', '0002_cliente_observations_alter_recorrencia_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 1.1.01, 2.3.05', max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='asaas_app.planocontas', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Asaas')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('PAYMENT', 'Pagamento Recebido'), ('PAYMENT_FEE', 'Taxa de Pagamento'), ('TRANSFER', 'Transferência'), ('TRANSFER_FEE', 'Taxa de Transferência'), ('REFUND', 'Reembolso'), ('CHARGEBACK', 'Chargeback'), ('ANTICIPATION', 'Antecipação'), ('ANTICIPATION_FEE', 'Taxa de Antecipação'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('status_conciliacao', models.CharField(choices=[('NAO_CONCILIADO', 'Não Conciliado'), ('CONCILIADO_AUTO', 'Conciliado Automaticamente'), ('CONCILIADO_MANUAL', 'Conciliado Manualmente')], default='NAO_CONCILIADO', max_length=20, verbose_name='Status de Conciliação')),
                ('observacoes_conciliacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dados_asaas', models.JSONField(blank=True, null=True, verbose_name='Dados Completos do Asaas')),
                ('synced_with_asaas', models.BooleanField(default=False, verbose_name='Sincronizado com Asaas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='asaas_app.cliente', verbose_name='Cliente')),
                ('recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='asaas_app.recorrencia', verbose_name='Recorrência')),
                ('plano_contas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='asaas_app.planocontas', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegraCategorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Regra')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('prioridade', models.IntegerField(default=0, help_text='Maior = mais prioridade', verbose_name='Prioridade')),
                ('campo', models.CharField(choices=[('descricao', 'Descrição'), ('tipo', 'Tipo de Movimentação'), ('cliente', 'Cliente')], max_length=50, verbose_name='Campo')),
                ('operador', models.CharField(choices=[('contem', 'Contém'), ('igual', 'Igual a'), ('comeca', 'Começa com'), ('termina', 'Termina com')], max_length=20, verbose_name='Operador')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('vezes_aplicada', models.IntegerField(default=0, verbose_name='Vezes Aplicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='asaas_app.planocontas', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Regra de Categorização',
                'verbose_name_plural': 'Regras de Categorização',
                'ordering': ['-prioridade', 'nome'],
            },
        ),
    ]
