# Generated by Django 5.0.1 on 2025-11-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_app', '0003_planocontas_movimentacao_regracategorizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para permitir valor livre', max_digits=10, null=True, verbose_name='Valor')),
                ('billing_type', models.CharField(choices=[('BOLETO', 'Boleto Bancário'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'Pix'), ('UNDEFINED', 'Perguntar ao Cliente')], default='UNDEFINED', max_length=20, verbose_name='Forma de Pagamento')),
                ('charge_type', models.CharField(choices=[('DETACHED', 'Avulso (valor fixo)'), ('INSTALLMENT', 'Parcelado'), ('RECURRENT', 'Recorrente (assinatura)')], default='DETACHED', max_length=20, verbose_name='Tipo de Cobrança')),
                ('due_date_limit_days', models.IntegerField(blank=True, help_text='Quantos dias após o acesso o link expira', null=True, verbose_name='Prazo de Vencimento (dias)')),
                ('max_installments', models.IntegerField(blank=True, help_text='Apenas para cobrança parcelada', null=True, verbose_name='Máximo de Parcelas')),
                ('asaas_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Asaas')),
                ('url', models.URLField(blank=True, help_text='Link público para compartilhar', max_length=500, null=True, verbose_name='URL do Link')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('EXPIRED', 'Expirado')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('synced_with_asaas', models.BooleanField(default=False, verbose_name='Sincronizado com Asaas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_pagamento', to='asaas_app.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Link de Pagamento',
                'verbose_name_plural': 'Links de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
