# Generated by Django 4.2.7 on 2026-02-09 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asaas_app', '0004_linkpagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_seguranca_reserva', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentual adicional sobre a média de despesas para reserva de caixa', max_digits=5, verbose_name='% Segurança da Reserva')),
                ('meses_media_reserva', models.IntegerField(default=6, help_text='Quantidade de meses anteriores para calcular a média de despesas', verbose_name='Meses para Média')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpfCnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('INDICADOR', 'Indicador'), ('SOCIO', 'Sócio')], max_length=20, verbose_name='Tipo')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, help_text='Percentual de comissão (ex: 10.00 = 10%)', max_digits=5, verbose_name='% Comissão')),
                ('majoritario', models.BooleanField(default=False, help_text='Sócios majoritários têm comissão calculada sobre resultado distribuível (após reserva de caixa)', verbose_name='Majoritário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(blank=True, help_text='Apenas sócios precisam de login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiro', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('total_receitas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Receitas')),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Despesas')),
                ('resultado_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Resultado Líquido')),
                ('media_despesas_6m', models.DecimalField(decimal_places=2, default=0, help_text='Média das despesas dos últimos N meses', max_digits=12, verbose_name='Média Despesas (últimos meses)')),
                ('percentual_seguranca', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentual de segurança aplicado no cálculo da reserva', max_digits=5, verbose_name='% Segurança Usado')),
                ('valor_reserva', models.DecimalField(decimal_places=2, default=0, help_text='Valor reservado para caixa (média × (1 + %segurança))', max_digits=12, verbose_name='Valor da Reserva')),
                ('resultado_distribuivel', models.DecimalField(decimal_places=2, default=0, help_text='Resultado líquido - reserva (mínimo 0)', max_digits=12, verbose_name='Resultado Distribuível')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ComissaoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_distribuivel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Resultado Distribuível')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_socio', to='asaas_app.fechamentomensal', verbose_name='Fechamento')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_socio', to='asaas_app.parceiro', verbose_name='Sócio')),
            ],
            options={
                'verbose_name': 'Comissão de Sócio',
                'verbose_name_plural': 'Comissões de Sócios',
                'ordering': ['-fechamento__ano', '-fechamento__mes'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Comissão')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês Referência')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano Referência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_indicador', to='asaas_app.cliente', verbose_name='Cliente')),
                ('fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_indicador', to='asaas_app.fechamentomensal', verbose_name='Fechamento')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes_indicador', to='asaas_app.movimentacao', verbose_name='Movimentação')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_indicador', to='asaas_app.parceiro', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Comissão de Indicador',
                'verbose_name_plural': 'Comissões de Indicadores',
                'ordering': ['-ano_referencia', '-mes_referencia'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='parceiro_indicador',
            field=models.ForeignKey(blank=True, help_text='Parceiro que indicou este cliente (opcional)', limit_choices_to={'ativo': True, 'tipo': 'INDICADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_indicados', to='asaas_app.parceiro', verbose_name='Parceiro Indicador'),
        ),
    ]
