# Generated by Django 4.2.7 on 2026-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_app', '0005_configuracaofinanceira_parceiro_fechamentomensal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentomensal',
            name='status',
            field=models.CharField(choices=[('PREVIO', 'Prévia'), ('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='PREVIO', max_length=20, verbose_name='Status'),
        ),
    ]
