# Generated by Django 4.2.7 on 2026-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asaas_app', '0006_alter_fechamentomensal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontas',
            name='excluir_do_fechamento',
            field=models.BooleanField(default=False, help_text='Marque para excluir movimentações desta categoria do cálculo do fechamento (ex: retirada de sócios)', verbose_name='Excluir do Fechamento'),
        ),
    ]
